name: quokki

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  alfred:
  json_annotation:
  mongo_dart:
  get_it:
  bcrypt: ^1.1.3
  calendar_time:
  dart_jsonwebtoken: ^2.8.1
  markdown: ^7.1.0

dev_dependencies:
  build_runner:
  json_serializable: